/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Post = IDL.Record({
  'categories' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'body' : IDL.Text,
  'slug' : IDL.Text,
  'datePublished' : IDL.Int,
  'author' : IDL.Text,
  'isDraft' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getDraftPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getPost' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
  'getPostCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPostsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'newPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Post = IDL.Record({
    'categories' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'body' : IDL.Text,
    'slug' : IDL.Text,
    'datePublished' : IDL.Int,
    'author' : IDL.Text,
    'isDraft' : IDL.Bool,
  });
  
  return IDL.Service({
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getDraftPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getPost' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
    'getPostCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPostsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'newPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };